easy_admin:
   entities:
        Recette:
            class: App\Entity\Recette
            form:
                fields: 
                    - { property: title }
                    - { property: photo }
                    - { property: description }
                    - { property: ingredientsList }
                    - { property: validate }
                    - { property: creation_date }
                    - { property: note }
                    - { property: user }
                    - { property: diet }
                    - { property: category }

        User:
            class: App\Entity\User
            form:
                fields: 
                    - { property: firstname }
                    - { property: lastname }
                    - { property: account_activate }
                    - { property: birthdate }
                    - { property: adresse }
                    - { property: city }
                    - { property: description }
                    - { property: username }
                    - { property: telephone }
                    - { property: roles }
                    - { property: recettes }
                    - { property: image }










        Category:
            class: App\Entity\Category

        Diet:
            class: App\Entity\Diet

        Note:
            class: App\Entity\Note



